version: '3.3'

services:
  db: 
    image: mysql:5.7 # Container de MySQL
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    env_file:
      - ./config/wp.env


volumes:
  db_data: {}     